language: python
python: 3.7-dev

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install --upgrade pip
  - pip install pipenv codecov
  - pipenv sync --dev

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov

after_success:
  - codecov